name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1'
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm audit --production
      - uses: actions/github-script@v6
        if: failure()
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Critical vulnerabilities found! Blocking merge until resolved.'
            })